development:
      host: localhost
      adapter: mysql
      database: fedena_development
      port: 3306
      username: root
      password: admin

test: &test
      host: localhost
      adapter: mysql
      database: fedena_two_new
      port: 3306
      username: root
      password: foradian

production:
      host: localhost
      adapter: mysql
      database: fedena_production
      port: 3306
      username: root
      password: admin
      
cucumber:
  <<: *test